version: '3'
networks:
  poc:
services:
  proxy-sql:
    image: proxysql/proxysql:latest
    volumes:
      - ./proxy-sql/proxysql.cnf:/etc/proxysql.cnf
      - ./proxy-sql/config.sql:/tmp/config.sql
    networks:
      - poc
    ports: 
      - 6033:6033
      - 6032:6032
    depends_on:
      - write-sql
      - read-sql
  write-sql:
    networks:
      - poc
    image: mysql:5.7.26
    volumes:
      - ./sql/create-db.sql:/docker-entrypoint-initdb.d/001.sql
      - ./sql/write-sql:/etc/mysql/conf.d
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=mysql
    ports:
      - 3306:3306
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8 --sql-mode=""
  read-sql:
    networks:
      - poc
    image: mysql:5.7.26
    volumes:
      - ./sql/create-db.sql:/docker-entrypoint-initdb.d/001.sql
      - ./sql/read-sql:/etc/mysql/conf.d
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_TCP_PORT=3307
    ports:
      - 3307:3307
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8 --sql-mode="" 


