version: '3'
networks:
  poc:
services:
  proxy-sql:
    build: ./proxy-sql
    volumes:
      - ./proxy-sql:/tmp
    networks:
      - poc
    environment: 
      - START_SLEEP=10
      - DB_USER=root
      - DB_PASSWORD=mysql
      - DB_SCHEMA_NAME=example-db
      - READER_ENDPOINT=read-sql:3307
      - WRITER_ENDPOINT=write-sql:3306
    ports: 
      - 6033:6033
      - 6032:6032
      - 6080:6080
  write-sql:
    networks:
      - poc
    image: mysql:5.7.26
    volumes:
      - ./sql/create-db.sql:/docker-entrypoint-initdb.d/001.sql
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=mysql
    ports:
      - 3306:3306
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8 --sql-mode=""
  read-sql:
    networks:
      - poc
    image: mysql:5.7.26
    volumes:
      - ./sql/create-db.sql:/docker-entrypoint-initdb.d/001.sql
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_TCP_PORT=3307
    ports:
      - 3307:3307
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8 --sql-mode="" 


